spring:
  profiles:
    active:
      - dev-8761
---
spring:
  profiles: dev-8761
  application:
    name: microcloud-eureka-8761
  security:
    user:
      name: admin
      password: 123456
server:
  port: 8761
eureka:
  instance:
    hostname: server1.phoenix.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://admin:123456@server2.phoenix.com:8762/eureka/,http://admin:123456@server3.pheonix.com:8763/eureka/
---
spring:
  profiles: dev-8762
  application:
    name: microcloud-eureka-8762
  security:
    user:
      name: admin
      password: 123456
server:
  port: 8762
eureka:
  instance:
    hostname: server2.phoenix.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://admin:123456@server1.phoenix.com:8761/eureka/,http://admin:123456@server3.pheonix.com:8763/eureka/

---
spring:
  profiles: dev-8763
  application:
    name: microcloud-eureka-8763
  security:
    user:
      name: admin
      password: 123456
server:
  port: 8763
eureka:
  instance:
    hostname: server3.phoenix.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://admin:123456@server2.phoenix.com:8762/eureka/,http://admin:123456@server1.pheonix.com:8761/eureka/