spring:
  application:
    name: springcloud-config-server
  profiles:
    active: native
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/xuwujing/springcloud-study/
#          search-paths: /springcloud-config/config-repo
#          username:
#          password:
server:
  port: 9005
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/